"""empty message

Revision ID: 2b846e05f03d
Revises: ee7c3ff3d7d8
Create Date: 2021-03-04 23:35:48.888503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b846e05f03d'
down_revision = 'ee7c3ff3d7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favoritos', 'usuario_id',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.create_foreign_key(None, 'favoritos', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.alter_column('favoritos', 'usuario_id',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
