"""empty message

Revision ID: ee7c3ff3d7d8
Revises: 031da6bf56c6
Create Date: 2021-03-04 23:20:21.885887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee7c3ff3d7d8'
down_revision = '031da6bf56c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoritos', sa.Column('usuario_id', sa.String(length=250), nullable=False))
    op.drop_column('favoritos', 'usuario_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoritos', sa.Column('usuario_name', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('favoritos', 'usuario_id')
    # ### end Alembic commands ###
